version: '2'
services:
  dockerapp:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    networks:
      - my_app

  reids:
    image: redis:3.2.0
    container_name: redis
    networks:
      - my_app
      
networks:
  my_app:
    driver: bridge